# Generated by Django 2.0 on 2020-02-05 16:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_mgmt', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usermaster',
            name='updated_at',
            field=models.DateTimeField(blank=True, default=None),
        ),
    ]
