# Generated by Django 2.0 on 2020-02-05 16:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_mgmt', '0002_auto_20200205_1644'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usermaster',
            name='updated_at',
            field=models.DateTimeField(blank=True, default=None, null=True),
        ),
    ]
